
// REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const CHECK_STATUS_FAILURE = 'CHECK_STATUS_FAILURE';
export const CHECK_STATUS_REQUEST =  'CHECK_STATUS_REQUEST';
export const CHECK_STATUS_SUCCESS = 'CHECK_STATUS_SUCCESS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// NOTIFICATION
export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';
export const RESET = 'RESET';


// PRODUCTS 
export const GET_PRODUCTS = "GET_PRODUCTS";



// CART
export const REMOVE_ITEM = "REMOVE_ITEM";
export const ADD_ITEM = "ADD_ITEM";
export const SET_CART = "SET_CART"
