/**
 * Action type constants to be used in the reducer and action creators.
 *
 * DO NOT EDIT THIS FILE!!
 */

export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const TOGGLE_PLAYER_STATUS = 'TOGGLE_PLAYER_STATUS';
