/** @format GENERAL
 * @description This is the entry point for the application. It renders the App-component to the DOM.
 * DO NOT EDIT THIS FILE
 * @module src/index.js
 * @see https://reactjs.org/docs/react-dom.html#render
 * @see https://reactjs.org/docs/react-dom-client.html#createroot
 */

import React from "react";
import { createRoot } from "react-dom/client";

import App from "./App.jsx";

// Redux stuff:
import { Provider } from "react-redux";
import store from "./redux/store.js";

const container = document.getElementById("root");
const root = createRoot(container);
root.render(
  <Provider store={store}>
    <React.StrictMode>
      <App />
    </React.StrictMode>
  </Provider>
);
